import { setCoreConfig } from "@pb/core/util";
import { initCoreGlobalsFromContent } from "@pb/core/lib/globals-init";
import {
  siteUrl,
  assetBaseUrl,
  person,
  siteMetadata,
  cdnBase,
  cdnTokenExpiryDays,
  cdnClientCacheExpiryHours,
  cdnApiCacheMaxAge,
  cdnApiCacheStaleWhileRevalidate,
  cdnAllowedHosts,
  cdnAllowedExtensions,
  imageDefaultWidth,
  imageDefaultPosterWidth,
  imagePosterWidth,
  imageMobileMaxWidth,
  imageMobileMaxWidth2x,
  imageDefaultQuality,
  imagePosterQuality,
  imageDefaultFormat,
  imageDefaultAspectRatio,
  imagePosterAspectRatio,
  imageClass,
  imagePosterClass,
  accessCookieName,
  accessCookieMaxAgeDays,
  rateLimitCookieName,
  rateLimitMaxAttempts,
  rateLimitLockoutMinutes,
  rateLimitCookieExpiryHours,
  formRateLimitMaxPerHour,
  uiBreakpointDesktopPx,
  uiNavHeightFallbackPx,
  uiPageBottomPaddingPx,
  uiMarqueeDefaultGapPx,
  uiTooltipGapDefaultPx,
  uiTooltipViewportPadPx,
  uiTooltipBridgeOverlapPx,
  uiTooltipMaxWidthPx,
  uiRangeDefaultBorderRadius,
  uiRangeThumbGlassBezelFactor,
  uiResizeDebounceMs,
  uiVideoPauseButtonHideDelayMs,
  uiHeroCarouselOpacityCurve,
  uiHeroCarouselPlaceholderBackgrounds,
  uiVideoDoubleTapThresholdMs,
  uiVideoHoldThresholdMs,
  uiVideoHoldRepeatMs,
  uiVideoFeedbackDurationMs,
  uiVideoSeekBackSeconds,
  uiVideoSeekForwardSeconds,
  uiVideoDefaultAspectRatio,
  cacheVideoUrlPrefix,
  uiIdleAfterMs,
  uiAudioSleepAfterMs,
  uiScrollDirectionThresholdPx,
  uiViewportThresholdSteps,
  uiVideoDefaultControlsList,
  threeAmbientIntensity,
  threeSpotAngle,
  threeSpotPenumbra,
  threeCameraBobbingAmount,
  threeCameraBobbingSpeed,
  threeCameraMouseSensitivity,
  threeCameraMouseSmoothness,
  threeSceneOrthoSize,
  threeScenePerspNear,
  threeNoiseOpacity,
  threeBloomLuminanceThreshold,
  threeBloomLuminanceSmoothing,
  threeBloomRadius,
  threeSsaoLuminanceInfluence,
  threeSsaoBias,
  threeSsaoFade,
  threeSsaoRangeThreshold,
  threeSsaoRangeFalloff,
  stringsAriaLabelContentBlock,
  stringsAriaLabelColumnLayout,
  stringsAriaLabelForm,
  stringsAriaLabelVideoQuality,
  stringsAriaLabelCarousel,
  stringsAriaLabelSectionScrollProgress,
  stringsAriaLabelNotifications,
  stringsAriaLabelDraggableContent,
  stringsLabelSubmitButton,
  stringsLabelSelectPlaceholder,
  stringsLabelTooltipTriggerClick,
  stringsLabelTooltipTriggerFocus,
  stringsLabelTooltipTriggerHover,
  stringsPlaceholderSearchInput,
  stringsErrorVideoSourceMissing,
  zIndexBase,
  zIndexRaised,
  zIndexContent,
  zIndexOverlay,
  zIndexColumnGrid,
  zIndexFixedSection,
  defaultTheme,
  colorTooltipBg,
  colorInputText,
  colorImageCompareHandle,
  colorLight3d,
  colorVideoPlaceholderBg,
  colorVideoErrorText,
  colorVideoErrorBg,
  colorVideoErrorBlur,
  colorMarqueeGradientEdgeFallback,
} from "@/core/lib/globals";
import { configureRuntimeGlobals } from "@pb/runtime-react/core/lib/globals";
import { initAnalytics, getAnalyticsOptions } from "@/core/lib/analytics";
import { validateRequiredRuntimeEnv } from "@/core/lib/required-runtime-env";
import { pbBuilderDefaultsV1 } from "@/app/theme/pb-builder-defaults";
import { pbContentGuidelines } from "@/app/theme/pb-content-guidelines";
import { pbCommittedWorkbenchElementDefaults } from "@/app/theme/pb-element-defaults";

let bootstrapped = false;

export function bootstrapCore(): void {
  if (bootstrapped) return;
  bootstrapped = true;

  validateRequiredRuntimeEnv();

  setCoreConfig({
    builderDefaults: {
      ...pbBuilderDefaultsV1,
      workbenchElements: pbCommittedWorkbenchElementDefaults,
    },
    contentGuidelines: pbContentGuidelines,
  });

  initCoreGlobalsFromContent();

  configureRuntimeGlobals({
    siteUrl,
    assetBaseUrl,
    person,
    siteMetadata,
    cdnBase,
    cdnTokenExpiryDays,
    cdnClientCacheExpiryHours,
    cdnApiCacheMaxAge,
    cdnApiCacheStaleWhileRevalidate,
    cdnAllowedHosts,
    cdnAllowedExtensions,
    imageDefaultWidth,
    imageDefaultPosterWidth,
    imagePosterWidth,
    imageMobileMaxWidth,
    imageMobileMaxWidth2x,
    imageDefaultQuality,
    imagePosterQuality,
    imageDefaultFormat,
    imageDefaultAspectRatio,
    imagePosterAspectRatio,
    imageClass,
    imagePosterClass,
    accessCookieName,
    accessCookieMaxAgeDays,
    rateLimitCookieName,
    rateLimitMaxAttempts,
    rateLimitLockoutMinutes,
    rateLimitCookieExpiryHours,
    formRateLimitMaxPerHour,
    uiBreakpointDesktopPx,
    uiNavHeightFallbackPx,
    uiPageBottomPaddingPx,
    uiMarqueeDefaultGapPx,
    uiTooltipGapDefaultPx,
    uiTooltipViewportPadPx,
    uiTooltipBridgeOverlapPx,
    uiTooltipMaxWidthPx,
    uiRangeDefaultBorderRadius,
    uiRangeThumbGlassBezelFactor,
    uiResizeDebounceMs,
    uiVideoPauseButtonHideDelayMs,
    uiHeroCarouselOpacityCurve,
    uiHeroCarouselPlaceholderBackgrounds,
    uiVideoDoubleTapThresholdMs,
    uiVideoHoldThresholdMs,
    uiVideoHoldRepeatMs,
    uiVideoFeedbackDurationMs,
    uiVideoSeekBackSeconds,
    uiVideoSeekForwardSeconds,
    uiVideoDefaultAspectRatio,
    cacheVideoUrlPrefix,
    uiIdleAfterMs,
    uiAudioSleepAfterMs,
    uiScrollDirectionThresholdPx,
    uiViewportThresholdSteps,
    uiVideoDefaultControlsList,
    threeAmbientIntensity,
    threeSpotAngle,
    threeSpotPenumbra,
    threeCameraBobbingAmount,
    threeCameraBobbingSpeed,
    threeCameraMouseSensitivity,
    threeCameraMouseSmoothness,
    threeSceneOrthoSize,
    threeScenePerspNear,
    threeNoiseOpacity,
    threeBloomLuminanceThreshold,
    threeBloomLuminanceSmoothing,
    threeBloomRadius,
    threeSsaoLuminanceInfluence,
    threeSsaoBias,
    threeSsaoFade,
    threeSsaoRangeThreshold,
    threeSsaoRangeFalloff,
    stringsAriaLabelContentBlock,
    stringsAriaLabelColumnLayout,
    stringsAriaLabelForm,
    stringsAriaLabelVideoQuality,
    stringsAriaLabelCarousel,
    stringsAriaLabelSectionScrollProgress,
    stringsAriaLabelNotifications,
    stringsAriaLabelDraggableContent,
    stringsLabelSubmitButton,
    stringsLabelSelectPlaceholder,
    stringsLabelTooltipTriggerClick,
    stringsLabelTooltipTriggerFocus,
    stringsLabelTooltipTriggerHover,
    stringsPlaceholderSearchInput,
    stringsErrorVideoSourceMissing,
    zIndexBase,
    zIndexRaised,
    zIndexContent,
    zIndexOverlay,
    zIndexColumnGrid,
    zIndexFixedSection,
    defaultTheme,
    colorTooltipBg,
    colorInputText,
    colorImageCompareHandle,
    colorLight3d,
    colorVideoPlaceholderBg,
    colorVideoErrorText,
    colorVideoErrorBg,
    colorVideoErrorBlur,
    colorMarqueeGradientEdgeFallback,
  });

  initAnalytics(getAnalyticsOptions());
}

export { getAnalyticsOptions } from "@/core/lib/analytics";
