// Auto-generated by scripts/download-webfonts.ts
// When true, layout.tsx uses self-hosted font files instead of fonts.bunny.net.
// Config hash: 19266c4296af7ff4 — regenerated when font config or source URLs change.
export const SELF_HOSTED = true;
