import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";
import { discoverAllPages } from "@pb/core/load";
import { isPageProtected } from "@/core/lib/page-protection";

const OUT_PATH = fileURLToPath(new URL("./protected-slugs.generated.ts", import.meta.url));

function isPasswordProtected(contentPath: string): boolean {
  try {
    const raw = fs.readFileSync(contentPath, "utf-8");
    const data = JSON.parse(raw) as { passwordProtected?: boolean; visibility?: string };
    return isPageProtected(data);
  } catch (err) {
    console.warn("[web-core] Failed to read page for password protection check", contentPath, err);
    return false;
  }
}

export async function getProtectedPagePaths(): Promise<string[]> {
  const pages = await discoverAllPages();
  return pages
    .filter((page) => isPasswordProtected(page.contentPath))
    .map((page) => page.slugSegments.join("/"))
    .filter((slugPath) => slugPath.length > 0)
    .sort((a, b) => a.localeCompare(b));
}

function buildOutputContent(paths: string[]): string {
  const entries = paths.map((s) => `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`).join(", ");
  return `// Generated by scripts/generate-protected-slugs.ts — do not edit by hand.
// Used by proxy to gate protected pages without loading page JSON at request time.

export const PROTECTED_PAGE_PATHS = new Set<string>([${entries}]);
`;
}

export async function regenerateProtectedSlugsFile(): Promise<void> {
  const paths = await getProtectedPagePaths();
  fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
  fs.writeFileSync(OUT_PATH, buildOutputContent(paths), "utf-8");
}
