/**
 * Committed production element defaults for builder defaults injection.
 *
 * These are the default variant configurations for all element types, used as
 * `workbenchElements` in the builder defaults pipeline. They match what the
 * dev workbench "production" defaults return, without importing from `/dev/*`.
 *
 * Source of truth: the variant defaults generated by `createPbBuilderDefaultsFromFoundations`
 * in packages/core. Colors/fonts are managed in their own config files.
 */
import type { PbWorkbenchElementDefaults } from "@pb/core/defaults";

// ---------------------------------------------------------------------------
// Workbench/legacy element defaults (variant fallbacks for dev tools)
// ---------------------------------------------------------------------------

/**
 * Committed workbench element defaults for production.
 *
 * These provide stable variant fallbacks for elements that don't have
 * a dedicated defaults pipeline (richText, videoTime, vector, svg, etc.).
 */
export const pbCommittedWorkbenchElementDefaults: PbWorkbenchElementDefaults = {
  richText: { v: 1, defaultVariant: "standard", variants: {} },
  videoTime: { v: 1, defaultVariant: "default", variants: {} },
  vector: { v: 1, defaultVariant: "icon", variants: {} },
  svg: { v: 1, defaultVariant: "icon", variants: {} },
  model3d: { v: 1, defaultVariant: "orbit", variants: {} },
  rive: { v: 1, defaultVariant: "default", variants: {} },
  scrollProgressBar: { v: 1, defaultVariant: "line", variants: {} },
};
